openapi: 3.1.0
info:
  title: Scratch Status Monitor Backend
  description: >
    ## はじめに


    このプロジェクトは、[Scratch](https://scratch.mit.edu)
    サービスの様々な機能の稼働状況を監視して、ユーザーにわかりやすく伝えることを目的としています。


    ## 注意事項


    ### 公開範囲


    リソースの節約と、運用費用を抑えるためこの API を一般公開することは推奨されません。


    ---


    [Scratch](https://scratch.mit.edu/)
    は、[MITメディアラボ](https://www.media.mit.edu/)の [Lifelong
    Kindergarten](https://www.media.mit.edu/groups/lifelong-kindergarten/overview/)
    グループによって開発されました。詳細は [https://scratch.mit.edu](https://scratch.mit.edu)
    をご覧ください。
  version: 0.0.1
  contact:
    name: Developer
    url: https://github.com/scratchcore
    email: contact@scratchcore.org
  license:
    name: GNU AGPLv3
    url: https://choosealicense.com/licenses/agpl-3.0
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: TXT
      description: Bearer Token
  schemas:
    UnauthorizedError:
      description: RFC 9457 (https://datatracker.ietf.org/doc/rfc9457) アクセス権限エラー
      example:
        type: https://datatracker.ietf.org/doc/rfc9457
        status: 401
        title: Unauthorized
        detail: You are not authorized to access this resource.
        invalid-params:
          - name: token
            reason: Missing or invalid
            location: header
      type: object
      properties:
        type:
          description: URL
          example: https://datatracker.ietf.org/doc/rfc9457
          type: string
          format: uri
        status:
          description: HTTPステータスコード（401）
          example: 401
          type: number
        title:
          description: エラーのタイトル
          example: Unauthorized
          type: string
        detail:
          description: 詳細エラー情報
          example: ログインが必要です。
          type: string
        invalid-params:
          description: 不正なパラメータの詳細リスト
          type: array
          items:
            type: object
            properties:
              name:
                description: 無効なパラメータ名
                example: email
                type: string
              reason:
                description: 理由
                example: Invalid format
                type: string
              location:
                description: パラメータの位置
                example: body
                type: string
            required:
              - name
              - reason
            additionalProperties: false
      required:
        - type
        - status
        - title
      additionalProperties: {}
security:
  - bearerAuth: []
servers:
  - url: http://localhost:8080
    description: Local Server
tags:
  - name: Examples
    description: |
      # Examples
externalDocs:
  description: GitHub
  url: https://github.com/scratchcore/scratch-status-monitor
paths:
  /:
    get:
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
      operationId: getIndex
      tags:
        - Examples
      parameters:
        - in: query
          name: name
          schema:
            description: The name of the user
            example: Steven
            type: string
      summary: Welcome
      description: Say hello to the user
