/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LocaleRouteRouteImport } from './routes/$locale/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as SSplatRouteImport } from './routes/s/$'
import { Route as ApiMetricsRouteImport } from './routes/api/metrics'
import { Route as LocaleTeamRouteImport } from './routes/$locale/team'
import { Route as LocaleFundingRouteImport } from './routes/$locale/funding'
import { Route as LocaleFeedbackRouteImport } from './routes/$locale/feedback'
import { Route as LocaleAboutRouteImport } from './routes/$locale/about'
import { Route as Locale404RouteImport } from './routes/$locale/404'
import { Route as LocaleSplatRouteImport } from './routes/$locale/$'
import { Route as LocalePoliciesIndexRouteImport } from './routes/$locale/policies/index'
import { Route as LocalePoliciesPolicyIdRouteImport } from './routes/$locale/policies/$policyId'

const LocaleRouteRoute = LocaleRouteRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const SSplatRoute = SSplatRouteImport.update({
  id: '/s/$',
  path: '/s/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMetricsRoute = ApiMetricsRouteImport.update({
  id: '/api/metrics',
  path: '/api/metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleTeamRoute = LocaleTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleFundingRoute = LocaleFundingRouteImport.update({
  id: '/funding',
  path: '/funding',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleFeedbackRoute = LocaleFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleAboutRoute = LocaleAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const Locale404Route = Locale404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocaleSplatRoute = LocaleSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePoliciesIndexRoute = LocalePoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => LocaleRouteRoute,
} as any)
const LocalePoliciesPolicyIdRoute = LocalePoliciesPolicyIdRouteImport.update({
  id: '/policies/$policyId',
  path: '/policies/$policyId',
  getParentRoute: () => LocaleRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/404': typeof Locale404Route
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/feedback': typeof LocaleFeedbackRoute
  '/$locale/funding': typeof LocaleFundingRoute
  '/$locale/team': typeof LocaleTeamRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/s/$': typeof SSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/policies/$policyId': typeof LocalePoliciesPolicyIdRoute
  '/$locale/policies/': typeof LocalePoliciesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/404': typeof Locale404Route
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/feedback': typeof LocaleFeedbackRoute
  '/$locale/funding': typeof LocaleFundingRoute
  '/$locale/team': typeof LocaleTeamRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/s/$': typeof SSplatRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/policies/$policyId': typeof LocalePoliciesPolicyIdRoute
  '/$locale/policies': typeof LocalePoliciesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRouteRouteWithChildren
  '/$locale/$': typeof LocaleSplatRoute
  '/$locale/404': typeof Locale404Route
  '/$locale/about': typeof LocaleAboutRoute
  '/$locale/feedback': typeof LocaleFeedbackRoute
  '/$locale/funding': typeof LocaleFundingRoute
  '/$locale/team': typeof LocaleTeamRoute
  '/api/metrics': typeof ApiMetricsRoute
  '/s/$': typeof SSplatRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/policies/$policyId': typeof LocalePoliciesPolicyIdRoute
  '/$locale/policies/': typeof LocalePoliciesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/$locale/$'
    | '/$locale/404'
    | '/$locale/about'
    | '/$locale/feedback'
    | '/$locale/funding'
    | '/$locale/team'
    | '/api/metrics'
    | '/s/$'
    | '/$locale/'
    | '/$locale/policies/$policyId'
    | '/$locale/policies/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale/$'
    | '/$locale/404'
    | '/$locale/about'
    | '/$locale/feedback'
    | '/$locale/funding'
    | '/$locale/team'
    | '/api/metrics'
    | '/s/$'
    | '/$locale'
    | '/$locale/policies/$policyId'
    | '/$locale/policies'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/$locale/$'
    | '/$locale/404'
    | '/$locale/about'
    | '/$locale/feedback'
    | '/$locale/funding'
    | '/$locale/team'
    | '/api/metrics'
    | '/s/$'
    | '/$locale/'
    | '/$locale/policies/$policyId'
    | '/$locale/policies/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRouteRoute: typeof LocaleRouteRouteWithChildren
  ApiMetricsRoute: typeof ApiMetricsRoute
  SSplatRoute: typeof SSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/s/$': {
      id: '/s/$'
      path: '/s/$'
      fullPath: '/s/$'
      preLoaderRoute: typeof SSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/metrics': {
      id: '/api/metrics'
      path: '/api/metrics'
      fullPath: '/api/metrics'
      preLoaderRoute: typeof ApiMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/team': {
      id: '/$locale/team'
      path: '/team'
      fullPath: '/$locale/team'
      preLoaderRoute: typeof LocaleTeamRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/funding': {
      id: '/$locale/funding'
      path: '/funding'
      fullPath: '/$locale/funding'
      preLoaderRoute: typeof LocaleFundingRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/feedback': {
      id: '/$locale/feedback'
      path: '/feedback'
      fullPath: '/$locale/feedback'
      preLoaderRoute: typeof LocaleFeedbackRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/about': {
      id: '/$locale/about'
      path: '/about'
      fullPath: '/$locale/about'
      preLoaderRoute: typeof LocaleAboutRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/404': {
      id: '/$locale/404'
      path: '/404'
      fullPath: '/$locale/404'
      preLoaderRoute: typeof Locale404RouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/$': {
      id: '/$locale/$'
      path: '/$'
      fullPath: '/$locale/$'
      preLoaderRoute: typeof LocaleSplatRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/policies/': {
      id: '/$locale/policies/'
      path: '/policies'
      fullPath: '/$locale/policies/'
      preLoaderRoute: typeof LocalePoliciesIndexRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
    '/$locale/policies/$policyId': {
      id: '/$locale/policies/$policyId'
      path: '/policies/$policyId'
      fullPath: '/$locale/policies/$policyId'
      preLoaderRoute: typeof LocalePoliciesPolicyIdRouteImport
      parentRoute: typeof LocaleRouteRoute
    }
  }
}

interface LocaleRouteRouteChildren {
  LocaleSplatRoute: typeof LocaleSplatRoute
  Locale404Route: typeof Locale404Route
  LocaleAboutRoute: typeof LocaleAboutRoute
  LocaleFeedbackRoute: typeof LocaleFeedbackRoute
  LocaleFundingRoute: typeof LocaleFundingRoute
  LocaleTeamRoute: typeof LocaleTeamRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocalePoliciesPolicyIdRoute: typeof LocalePoliciesPolicyIdRoute
  LocalePoliciesIndexRoute: typeof LocalePoliciesIndexRoute
}

const LocaleRouteRouteChildren: LocaleRouteRouteChildren = {
  LocaleSplatRoute: LocaleSplatRoute,
  Locale404Route: Locale404Route,
  LocaleAboutRoute: LocaleAboutRoute,
  LocaleFeedbackRoute: LocaleFeedbackRoute,
  LocaleFundingRoute: LocaleFundingRoute,
  LocaleTeamRoute: LocaleTeamRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocalePoliciesPolicyIdRoute: LocalePoliciesPolicyIdRoute,
  LocalePoliciesIndexRoute: LocalePoliciesIndexRoute,
}

const LocaleRouteRouteWithChildren = LocaleRouteRoute._addFileChildren(
  LocaleRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRouteRoute: LocaleRouteRouteWithChildren,
  ApiMetricsRoute: ApiMetricsRoute,
  SSplatRoute: SSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
